version: '3.8'
services:
  dev-db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sounds-of-teyvat
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lifb/postgresql/data
    networks:
      - music-network
  test-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sounds-of-teyvat
    ports:
      - '5435:5432'
    networks:
      - music-network
volumes:
  db:
    driver: local
networks:
  music-network: